### ISSUE TITLE
Menu button does not display more options. It is still unable to clickable execution of this button.

### ISSUE THREAD

**Issue by suren122** [KcAvishek/collab-work#10]
For Front end developers. Please go for this issue seriously.

**Comment by Pranimadhakal** [comment]
![87e7533c-4cf9-46bf-a6cc-ba20ca68108e (1)](https://github.com/KcAvishek/collab-work/assets/119206664/29a94242-698d-447a-ac86-add6a4365d22)
i worked on this issue.
