### ISSUE TITLE
Not displaying the dates with specified ranges.

### ISSUE THREAD

**Issue by suren122** [KcAvishek/collab-work#11]
For Backend developers. Please go for this issue seriously.

**Comment by KcAvishek** [comment]
i have done this work

**Comment by KcAvishek** [comment]
<img width="1251" alt="image" src="https://github.com/KcAvishek/collab-work/assets/123866650/c118d1f6-35d5-46b5-8d74-1e44969ba9ec">

**Comment by suren122** [comment]
Now it is working properly and the dates reports are showing in proper format. Thank you.
