### ISSUE TITLE
The submit button is not working after clicking it. It is not adding new tables.

### ISSUE THREAD

**Issue by suren122** [KcAvishek/collab-work#12]
For Front end developers. Please go for this issue seriously.

**Comment by KcAvishek** [comment]
This bug have been fixed

**Comment by niraj907** [comment]
Okayy I will fix it .

**Comment by KcAvishek** [comment]
adding  new table
<img width="1251" alt="image" src="https://github.com/KcAvishek/collab-work/assets/123866650/316070e4-7539-4056-ad58-5a1215cf4ddc">
added on the table.
<img width="1251" alt="image" src="https://github.com/KcAvishek/collab-work/assets/123866650/c220132e-08f5-437b-b644-b119a0665752">

**Comment by suren122** [comment]
Yes, I got it. You have done your job successfully.
