### ISSUE TITLE
No more information is displayed when clicked view details button in new bookings tablet form.

### ISSUE THREAD

**Issue by suren122** [KcAvishek/collab-work#13]
For both Backend and front developers. Please go for this issue seriously.
Backend functions are for backend member.
Frontend functions are for frontend member.

**Comment by KcAvishek** [comment]
ok sir i fix this issue

**Comment by KcAvishek** [comment]
when clicked on view details
<img width="1010" alt="image" src="https://github.com/KcAvishek/collab-work/assets/123866650/7e6be2e5-0e55-40d8-bdb2-6f0ddbb2049a">

**Comment by suren122** [comment]
Good Job. You did it..

**Comment by niraj907** [comment]
Okayy i will do

**Comment by suren122** [comment]
All right. I know You will do it.

**Comment by niraj907** [comment]
I have fix it . when admin will click to view details  it show the customer booking details
![image](https://github.com/KcAvishek/collab-work/assets/124789047/751d90d7-4291-4b2b-9e54-3c2c62ff21ed)

**Comment by niraj907** [comment]
![image](https://github.com/KcAvishek/collab-work/assets/124789047/c0fcb3e8-e4c1-4730-a996-fbbafc9fb4bb)

**Comment by niraj907** [comment]
Admin can now  rejected or accept of tablet booking
![image](https://github.com/KcAvishek/collab-work/assets/124789047/28d600d5-42c7-4af6-9066-108d7661c6bf)
