### ISSUE TITLE
Not displaying the count of total booking of customers.

### ISSUE THREAD

**Issue by suren122** [KcAvishek/collab-work#14]
For Back end developers. Please go for this issue seriously.
Front design is working properly but the data from database are not fetching in admin dashboard panel.

**Comment by KcAvishek** [comment]
<img width="1010" alt="image" src="https://github.com/KcAvishek/collab-work/assets/123866650/c67ef124-9086-423c-a8a9-50698615ee22">

**Comment by suren122** [comment]
All right, you have done your job successfully.

**Comment by niraj907** [comment]
Okayy friend i will fix it.

**Comment by niraj907** [comment]
Now it is show the total count table booking
  ![image](https://github.com/KcAvishek/collab-work/assets/124789047/d8bfe4ba-f133-41e7-ad0e-bd02d25f56ad)

**Comment by suren122** [comment]
Thanks my friend, the total number of booking is displaying exactly.

**Comment by niraj907** [comment]
Displaying all booking detail ![image](https://github.com/KcAvishek/collab-work/assets/124789047/d1f5f414-468b-4cb8-9eab-165476f4d6e2)
