### ISSUE TITLE
I observed the bad location of submit button in table booking panel. And Also the number of customer can not be in negative number. 

### ISSUE THREAD

**Issue by suren122** [KcAvishek/collab-work#2]
Go for this issue seriously. Especially this task is assigned for my front end team member.

**Comment by KcAvishek** [comment]
ok i have done

**Comment by suren122** [comment]
Ok you are the best. Thank You so much.

**Comment by KcAvishek** [comment]
i have  done

**Comment by Pranimadhakal** [comment]
i did some changes in the CSS file and the issue is solved.
 
![image](https://github.com/KcAvishek/collab-work/assets/119206664/f064a9f3-e557-4f86-9e65-a7a2a9321912)
