### ISSUE TITLE
Admin Dashboard work ( Drop down of slide bar)

### ISSUE THREAD

**Issue by KcAvishek** [KcAvishek/collab-work#4]
This is just a frontend work that concerns the slide bar of the Admin Dashboard. Using this feature, we are able to see add and  manage on tables also new, accepted and rejected on bookings.

**Comment by nirbhayahub04** [comment]
Hello Avishek I have done the following requirements and pushed it to my Branch.
This is the ss of The Sidebar after change.

![Screenshot 2024-05-17 150729](https://github.com/KcAvishek/collab-work/assets/120441267/e006da0e-75ec-47fa-94e7-1c466e831d86)
