### ISSUE TITLE
Make the side bar responsive.

### ISSUE THREAD

**Issue by Pranimadhakal** [KcAvishek/collab-work#5]
The sidebar of the admin dashboard is not responsive, so make sure to make it responsive.

**Comment by nirbhayahub04** [comment]
I've successfully implemented responsive design and enhanced navigation features in the sidebar to ensure improved user satisfaction and experience.
![Screenshot 2024-04-22 141452](https://github.com/KcAvishek/collab-work/assets/120441267/b13ad03e-f906-4348-9a55-4ff88f31c554)
![Screenshot 2024-04-22 141219 - Copy](https://github.com/KcAvishek/collab-work/assets/120441267/69cf1cac-716d-4884-8911-9eb35345616b)
