### ISSUE TITLE
Please make the table more visible and accessible for admin.

### ISSUE THREAD

**Issue by nirbhayahub04** [KcAvishek/collab-work#6]
The table in the admin panel is not big enough for the admin to see. So, please make changes in the size of the table. Also try making it more formal.

**Comment by Pranimadhakal** [comment]
I have made the table more visible and more accessible for the admin hope you find that good
here the screen shots of that table.
![Screenshot 2024-04-22 150546](https://github.com/KcAvishek/collab-work/assets/119206664/d5745dd3-16bd-4378-b652-a7d99c05a27f)
