### ISSUE TITLE
Add a 'Take Action' button in the Booking Table page.

### ISSUE THREAD

**Issue by nirbhayahub04** [KcAvishek/collab-work#7]
Add a new button 'Take Action' in the booking table page so that the admin can update the bookings. The update page should be a simple pop-up which is displayed in the center of the screen.

**Comment by Pranimadhakal** [comment]
![Screenshot 2024-04-22 150008](https://github.com/KcAvishek/collab-work/assets/119206664/14c781cb-4a70-4863-841c-c10a43c15dc3)
here, i have successfully created a new take action button which gives a pop up menu to change update booking system. write properly.
