### ISSUE TITLE
Navigation bar is not fixed

### ISSUE THREAD

**Issue by suren122** [KcAvishek/collab-work#8]
For Front end team members. please go for this issue Seriously.

**Comment by nirbhayahub04** [comment]
![Screenshot 2024-05-17 232259](https://github.com/KcAvishek/collab-work/assets/120441267/afafa693-5d41-4ef5-b48f-7e04cd0422dd)
Here I have made the navbar fix and also made the nav bar Responsive please check the main branch for the Fixed bug

**Comment by suren122** [comment]
Hm, this looked nice. I got it successfully. Thank you.
