### ISSUE TITLE
The plates are rotating rapidly.

### ISSUE THREAD

**Issue by suren122** [KcAvishek/collab-work#9]
For Front end developers. Please go for this issue seriously.

**Comment by nirbhayahub04** [comment]
![Screenshot 2024-05-17 230544](https://github.com/KcAvishek/collab-work/assets/120441267/3417822f-75bb-4a49-8c86-138aa25fffee)
Hello Suren I have Adjusted the speed of the the Plates please check My branch for the upgraded Codes.

**Comment by suren122** [comment]
Ok My friends, I got it. Now this is solved with normal rotation of plates.
